### ISSUE TITLE
adios_reorganize segfault

### ISSUE THREAD

**Issue by NAThompson** [ornladios/ADIOS2#2147]
Using:

```
$ bpls -v --version   
blps: ADIOS file introspection utility

Build configuration:
ADIOS version: 2.5.0.784 (c43a97b5)
C++ Compiler:  AppleClang 11.0.0.11000033
Target OS:     Darwin-18.7.0
Target Arch:   x86_64
```

and `adios_reorganize`, we have the following segfault:

```
$ adios_reorganize tris-blocks.bp tris-blocks2.bp
 adios_reorganize tris-blocks.bp tris-blocks2.bp rmethod="BPFile" wmethod "BPFile"
AddressSanitizer:DEADLYSIGNAL
=================================================================
==24712==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fff5bc986f2 bp 0x7ffee8a79040 sp 0x7ffee8a79040 T0)
==24712==The signal is caused by a READ memory access.
==24712==Hint: address points to the zero page.
    #0 0x7fff5bc986f1 in _platform_strlen (libsystem_platform.dylib:x86_64+0x16f1)
    #1 0x1085ce309 in wrap_strlen (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x18309)
    #2 0x10718ad4c in std::__1::char_traits<char>::length(char const*) __string:218
    #3 0x1071d31a3 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<std::nullptr_t>(char const*) string:820
    #4 0x10718ef96 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<std::nullptr_t>(char const*) string:818
    #5 0x1071908f9 in adios2::utils::Reorganize::Reorganize(int, char**) Reorganize.cpp:75
    #6 0x1071934ac in adios2::utils::Reorganize::Reorganize(int, char**) Reorganize.cpp:52
    #7 0x1071880eb in main main.cpp:28
    #8 0x7fff5bab03d4 in start (libdyld.dylib:x86_64+0x163d4)

==24712==Register values:
rax = 0x000000010926768c  rbx = 0x00007ffee8a79e00  rcx = 0x0000000000000000  rdx = 0x0000000000000000  
rdi = 0x0000000000000000  rsi = 0x0000000000000000  rbp = 0x00007ffee8a79040  rsp = 0x00007ffee8a79040  
 r8 = 0x00007ffee8a7a501   r9 = 0x5b130c538cbe4401  r10 = 0x0000000000000000  r11 = 0x0000000000000af8  
r12 = 0x0000000109267688  r13 = 0x00007ffee8a79be0  r14 = 0x0000000000000000  r15 = 0x00007ffee8a79b60  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib:x86_64+0x16f1) in _platform_strlen
==24712==ABORTING
[1]    24712 abort      adios_reorganize tris-blocks.bp tris-blocks2.bp rmethod="BPFile" wmethod 
```

The file `tris-blocks.bp` is [here](https://gitlab.kitware.com/vtk/adis/-/blob/master/tests/data/tris-blocks.bp).

**Comment by pnorbert** [comment]
Missing the tris-blocks.bp.dir/ content

**Comment by NAThompson** [comment]
@pnorbert : It's fixed; no worries.

**Comment by pnorbert** [comment]
@NAThompson Oh, wrong argument list.
