### ISSUE TITLE
gsplot.py from Gray Scott  example is broken

### ISSUE THREAD

**Issue by dmitry-ganyushin** [ornladios/ADIOS2#4028]
The Stream function from python API  does not know about config parameters:

```
python ./gsplot.py -i file.bp -v ../data/ptj.field.bp/temp --plane=xz
Traceback (most recent call last):
  File "./gsplot.py", line 135, in <module>
    fr = Stream(args.instream, "r", comm=mpi.comm_app, config_file="adios2.xml",
  File "/home/ganyush/anaconda3/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'config_file'
```

**Comment by pnorbert** [comment]
In the master branch [examples/simulations/gray-scott/plot/gsplot.py](https://github.com/ornladios/ADIOS2/blob/master/examples/simulations/gray-scott/plot/gsplot.py)  does not look like that:
```
    adios = Adios("adios2.xml", mpi.comm_app)
    io = adios.declare_io("SimulationOutput")
    fr = Stream(io, args.instream, "r", mpi.comm_app)
```

What version of the script are you looking at?

**Comment by dmitry-ganyushin** [comment]
That can be indeed fixed by update. The second problem appears:
```
> /home/ganyush/ADIOS2/lib/python3.8/site-packages/adios2/adios.py(20)__init__()
-> self.impl = bindings.ADIOS(config_file, comm)
(Pdb) s
*** The MPI_Comm_dup() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[bulldozer:11133] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Comment by dmitry-ganyushin** [comment]
It looks like campaign engine does not send available variables to python bindings.
```
bpls  -E Campaign  test_s3d_31.aca  
hostname: PC0136094
Errno was 111
  double   ../data/ptj.field.bp/pressure  31*{2560, 960, 3456}
  double   ../data/ptj.field.bp/species   31*{19, 2560, 960, 3456}
  double   ../data/ptj.field.bp/temp      31*{2560, 960, 3456}
  double   ../data/ptj.field.bp/uvel      31*{2560, 960, 3456}
  double   ../data/ptj.field.bp/vvel      31*{2560, 960, 3456}
  double   ../data/ptj.field.bp/wvel      31*{2560, 960, 3456}
```

```
>>> import adios2
>>> adios = adios2.Adios("adios2.xml")
>>> fr = Stream(io, "test_s3d_31.aca", "r")
>>> io = adios.declare_io("SimulationOutput")
>>> fr = adios2.Stream(io, "test_s3d_31.aca", "r")
hostname: PC0136094
Errno was 111
>>> fr.available_variables()
{}
```

**Comment by dmitry-ganyushin** [comment]
The same for the C++ bindings:
```
        adios2::ADIOS adios("adios2.xml");

        /*** IO class object: settings and factory of Settings: Variables,
         * Parameters, Transports, and Execution: Engines */
        adios2::IO bpIO = adios.DeclareIO("SimulationOutput");

        /** Engine derived class, spawned to start IO operations */
        adios2::Engine bpReader = bpIO.Open("test_s3d_31.aca", adios2::Mode::Read);

        bpReader.BeginStep();
        const std::map<std::string, adios2::Params> variables = bpIO.AvailableVariables();
```

**Comment by dmitry-ganyushin** [comment]
The c++ example can be fixed by using the  RandomAccessRead mode.
In python FileReader which uses "rra" mode should be used.

**Comment by pnorbert** [comment]
Thanks for checking, now I remember that the campaign engine doesn't
support stream read mode yet. That should be the fix for this problem.

gsplot cannot use the FileReader as it must support the staging examples.
