### ISSUE TITLE
Test fails on local Debian

### ISSUE THREAD

**Issue by kshitij-v-mehta** [ornladios/ADIOS2#4140]
The `TestBPWriteTypesHighLevelAPI.py` test fails on a local Debian machine for ADIOS release 2.10 built using gcc 12.2.0.

```
mpirun -np 2 python3 TestBPWriteTypesHighLevelAPI.py
type of i = <class 'int'>, type of f = <class 'float'>, type of c = <class 'complex'>
---- type of np.array(data.i8[0]) is <class 'numpy.ndarray'> shape = ()
tag = Testing ADIOS2 high-level API
nx = 10
Traceback (most recent call last):
  File "/media/psf/vshare/sw/ADIOS2-2.10.0/testing/adios2/python/TestBPWriteTypesHighLevelAPI.py", line 450, in <module>
Traceback (most recent call last):
  File "/media/psf/vshare/sw/ADIOS2-2.10.0/testing/adios2/python/TestBPWriteTypesHighLevelAPI.py", line 188, in <module>
    raise ValueError("gvarU8 read failed")
ValueError: gvarU8 read failed
    indataU8 = fr_step.read("varU8", start, count)
  File "/home/kmehta/opt/miniconda3/envs/adios2.10/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/kmehta/vshare/sw/ADIOS2-2.10.0/installation/lib/python3.10/site-packages/adios2/stream.py", line 452, in _
    return self.read(variable, start, count, block_id, step_selection)
  File "/home/kmehta/opt/miniconda3/envs/adios2.10/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/kmehta/vshare/sw/ADIOS2-2.10.0/installation/lib/python3.10/site-packages/adios2/stream.py", line 420, in read
    return self._read_var(variable)
  File "/home/kmehta/vshare/sw/ADIOS2-2.10.0/installation/lib/python3.10/site-packages/adios2/stream.py", line 374, in _read_var
    self._engine.get(variable, output)
  File "/home/kmehta/vshare/sw/ADIOS2-2.10.0/installation/lib/python3.10/site-packages/adios2/engine.py", line 140, in get
    self.impl.Get(variable.impl, content, mode)
ValueError: In ADIOS2 Get - Type mismatch between Python buffer and incoming data.
```

**Comment by eisenhauer** [comment]
@kshitij-v-mehta Can verify that the PR fixed this, so we can close it?

**Comment by kshitij-v-mehta** [comment]
Sorry for the late reply. I can confirm that the example works now. Also, I noticed that the PR was merged into the release_210 branch, and that the changes are not yet in the main branch. Just fyi.
