### ISSUE TITLE
regression test failure with mpi4py 4.0.0

### ISSUE THREAD

**Issue by chenrui333** [ornladios/ADIOS2#4270]
👋 trying to upgrade mpi4py to 4.0.0, but run into some regression test failure with ADIOS2 2.10.1. The error log is as below:

<details>
<summary>error test log</summary>

```
==> mpic++ /opt/homebrew/Cellar/adios2/2.10.1/share/adios2/test/bpWriter.cpp -DADIOS2_USE_MPI -isystem /opt/homebrew/Cellar/adios2/2.10.1/include -std=gnu++11 /opt/homebrew/Cellar/adios2/2.10.1/lib/libadios2_cxx11_mpi.2.10.1.dylib /opt/homebrew/Cellar/adios2/2.10.1/lib/libadios2_cxx11.2.10.1.dylib
  ==> ./a.out
  [Mac-1722175340188.local:11221] shmem: mmap: an error occurred while determining whether or not /private/tmp/ompi.Mac-1722175340188.501/jf.0/4149280768/sm_segment.Mac-1722175340188.501.f7510000.0 could be created.
  Wrote file myVector_cpp.bp to disk. It can now be read by running ./bin/adios2_hello_bpReader.
  ==> python3.12 -c import adios2
  ==> python3.12 /opt/homebrew/Cellar/adios2/2.10.1/share/adios2/test/bpWriter.py
  [Mac-1722175340188.local:11224] shmem: mmap: an error occurred while determining whether or not /private/tmp/ompi.Mac-1722175340188.501/jf.0/1494089728/sm_segment.Mac-1722175340188.501.590e0000.0 could be created.
  ValueError: mpi4py.MPI.Op size changed, may indicate binary incompatibility. Expected [56](https://github.com/Homebrew/homebrew-core/actions/runs/10132279154/job/28016502552?pr=178758#step:3:57) from C header, got 40 from PyObject
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/adios2/2.10.1/share/adios2/test/bpWriter.py", line 28, in <module>
      adios = adios2.Adios(config_file=None, comm=comm)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/lib/python3.12/site-packages/adios2/adios.py", line 25, in __init__
      self.impl = bindings.ADIOS(comm)
                  ^^^^^^^^^^^^^^^^^^^^
  RuntimeError: ERROR: mpi4py not loaded correctly
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/10132279154/job/28016502552?pr=178758
relates to Homebrew/homebrew-core#178758

**Comment by chenrui333** [comment]
Looks like just a rev update would do the job.
