### ISSUE TITLE
Failure in Install.Make.* tests in macos

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#4272]
The C and C++ version fails with the following error:

Same error in `Test.Engine.DataManSingleValues` and `Test.Engine.DataMan1xN.Serial`.
```
E
======================================================================
ERROR: test_run (__main__.TestDataMan1D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/ADIOS2/ADIOS2/source/testing/adios2/engine/dataman/TestDataManSingleValues.py", line 34, in test_run
    s.start()
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object

----------------------------------------------------------------------
Ran 1 test in 0.015s

FAILED (errors=1)
```

**Comment by vicentebolea** [comment]
These errors still occur
