### ISSUE TITLE
 Failure in some dataman tests in macos

### ISSUE THREAD

**Issue by vicentebolea** [ornladios/ADIOS2#4273]
Same error in `Test.Engine.DataManSingleValues` and `Test.Engine.DataMan1xN.Serial`.
```
E
======================================================================
ERROR: test_run (__main__.TestDataMan1D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/ADIOS2/ADIOS2/source/testing/adios2/engine/dataman/TestDataManSingleValues.py", line 34, in test_run
    s.start()
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/runner/miniconda3/envs/adios2/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object

----------------------------------------------------------------------
Ran 1 test in 0.015s

FAILED (errors=1)
```

**Comment by eisenhauer** [comment]
I've seen this, but it's a python thing, not Dataman.  Something about multiprocessing if I recall, but I'd have to go back and see if I remember what the fix for this was.

**Comment by eisenhauer** [comment]
https://github.com/ornladios/ADIOS2/pull/3687

**Comment by vicentebolea** [comment]
Removed stale since these tests are disable and we need to check if we can enable them again

**Comment by eisenhauer** [comment]
Are these tests disabled?  I was just looking to see and if they are I don't see the mechanism through which they are being turned off...

**Comment by vicentebolea** [comment]
We exclude them at https://github.com/ornladios/ADIOS2/blob/61025332781ed1215d9c92c0d70747db90b2e38b/scripts/ci/cmake/ci-macos-14-xcode15_4-shared-serial.cmake#L39 and https://github.com/ornladios/ADIOS2/blob/61025332781ed1215d9c92c0d70747db90b2e38b/scripts/ci/cmake/ci-macos-13-xcode14_2-shared-serial.cmake#L39
